// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gefnujrliokeuwybvktl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlZm51anJsaW9rZXV3eWJ2a3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDAzMjIsImV4cCI6MjA2ODI3NjMyMn0.s5nEDVTXu1Kq4zQuAAioFePWzIvpf_lshOF6LWglxWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});